# Ensure that a non-login, non-interactive shell has a defined environment.

if [ "$LS_COLORS" -a -f /etc/DIR_COLORS ]; then
  eval $(dircolors /etc/DIR_COLORS)
fi

export GOPATH=~/go
export JENV_SHELL=zsh
export JENV_LOADED=1
unset JAVA_HOME

export Z_PATH=$HOME/dotfiles/zsh2

export PATH="$PATH:$HOME/go/bin"
export PATH="$HOME/.nodebrew/current/bin:$PATH"
export PATH="$GOROOT/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"
export PATH="$HOME/.jenv/shims:$PATH"
export PATH="$HOME/CyberAgent/dynalyst-mgmt-fm-tool:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="${HOME}/.scalaenv/bin:${PATH}"
export PATH="${HOME}/mybin:${PATH}"

export LSCOLORS=cxfxcxdxbxGxDxabagacad

export FZF_CTRL_T_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_CTRL_T_OPTS='--reverse --preview "bat --color=always --style=header,grid --line-range :100 {}"'
export FZF_CTRL_R_OPTS='--reverse'


