# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
eval "$(fig init zsh pre)"

for f in ${Z_PATH}/myconf/*; do
	if [ -d $f ]; then
		for file in $f/*; do
			source $file
		done
	fi
	if [ -f $f ]; then
		if grep -q tmux_conf $f; then
			continue
		fi
		source $f
	fi
done

source ${HOME}/tools/z/z.sh
source ${HOME}/tools/zsh-abbr/zsh-abbr.zsh

# Fig post block. Keep at the bottom of this file.
eval "$(fig init zsh post)"

source ${Z_PATH}/myconf/tmux_conf.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
