# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
for f in ${Z_PATH}/myconf/*; do
	if [ -d $f ]; then
		for file in $f/*; do
			source $file
		done
	fi
	if [ -f $f ]; then
		if grep -q tmux_conf $f; then
			continue
		fi
		source $f
	fi
done

source ${HOME}/tools/z/z.sh
source ${HOME}/tools/zsh-abbr/zsh-abbr.zsh
cp ${HOME}/tools/chrome-cli/chrome-cli/chrome-cli /usr/local/bin

source ${Z_PATH}/myconf/tmux_conf.zsh

# source ~/.cache/dein/repos/github.com/junegunn/fzf.vim/plugin/fzf.vim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=$PATH:~/.rbenv/bin

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
