# /Users/s11308/.config/tmuxinator/base.yml

name: base
root: ~/

windows:
  - main:
      layout: main-horizontal
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
          - tmuxinator start work
          - tmuxinator start apps
          - tmuxinator start formation
          - tmuxinator start sbt
          - sleep 5 && tmux kill-session -t base
