# Ensure that a non-login, non-interactive shell has a defined environment.

if [ "$LS_COLORS" -a -f /etc/DIR_COLORS ]; then
  eval $(dircolors /etc/DIR_COLORS)
fi

export GOPATH=$HOME/go
export PYENV_ROOT="$HOME/.pyenv"
export Z_PATH=$HOME/dotfiles/zsh

# ---- PATH (order matters — top is highest priority) ----
path=(
  # tools
  ${HOME}/tools/fzf-chrome-active-tab/chrome-tab-activate
  /opt/homebrew/opt/postgresql@13/bin

  # lang
  ${HOME}/.nodenv/shims
  ${HOME}/.jenv/shims
  ${HOME}/.scalaenv/shims

  # dotfiles/bin + subdirectories
  ${HOME}/dotfiles/bin/*(N/)
  ${HOME}/dotfiles/bin

  # work
  ${HOME}/CyberAgent/dynalyst-mgmt-fm-tool

  # system
  /opt/homebrew/bin

  $path

  # append (low priority)
  ${GOPATH}/bin
  ${HOME}/tools/cycloud
)

export LSCOLORS=cxfxcxdxbxGxDxabagacad


[[ -f /Users/s11308/tools/kube-ps1/kube-ps1.sh ]] && source /Users/s11308/tools/kube-ps1/kube-ps1.sh
