export SHELL=/bin/zsh

for f in ${Z_PATH}/myconf/*; do
	if [ -d $f ]; then
		for file in $f/*; do
			source $file
		done
	fi
	if [ -f $f ]; then
		if [[ "$(basename $f)" == "tmux_conf.zsh" ]]; then
			continue
		fi
		source $f
	fi
done

source ${HOME}/tools/z/z.sh
# Load zsh-abbr after zim.zsh so it binds in viins keymap (vi mode)
source /opt/homebrew/share/zsh-abbr/zsh-abbr.zsh
eval "$(abbr-loader $HOME/dotfiles/zsh/abbr/abbr.yaml)"

source ${Z_PATH}/myconf/tmux_conf.zsh

eval "$(direnv hook zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
