export SHELL=/bin/zsh


# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
for f in ${Z_PATH}/myconf/*; do
	if [ -d $f ]; then
		for file in $f/*; do
			source $file
		done
	fi
	if [ -f $f ]; then
		if grep -q tmux_conf $f; then
			continue
		fi
		source $f
	fi
done

source ${HOME}/tools/z/z.sh
# Load zsh-abbr after zim.zsh so it binds in viins keymap (vi mode)
source "$(brew --prefix)/share/zsh-abbr/zsh-abbr.zsh"
eval "$(abbr-loader $HOME/dotfiles/zsh/abbr/abbr.yaml)"

source ${Z_PATH}/myconf/tmux_conf.zsh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
eval "$(direnv hook zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
